name: Build KaraokeAI Studio PRO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installa Dipendenze
        run: |
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install customtkinter openai-whisper pillow numpy pyinstaller tiktoken

      - name: Download FFmpeg & FFprobe
        shell: pwsh
        run: |
          $u = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
          Invoke-WebRequest -Uri $u -OutFile ff.zip
          Expand-Archive ff.zip -DestinationPath temp
          $f = Get-ChildItem -Path "temp" -Recurse -Filter "ffmpeg.exe" | Select-Object -First 1
          $p = Get-ChildItem -Path "temp" -Recurse -Filter "ffprobe.exe" | Select-Object -First 1
          Copy-Item $f.FullName -Destination "ffmpeg.exe"
          Copy-Item $p.FullName -Destination "ffprobe.exe"

      - name: Pre-Download Modello Whisper
        run: |
          python -c "import whisper; whisper.load_model('base', download_root='whisper_models')"

      - name: Build EXE Definitivo
        shell: pwsh
        run: |
          pyinstaller --noconfirm --onefile --windowed `
            --name "KaraokeAI_Studio_Pro" `
            --add-binary "ffmpeg.exe;." `
            --add-binary "ffprobe.exe;." `
            --add-data "whisper_models;whisper_models" `
            --collect-all whisper `
            --collect-all customtkinter `
            --hidden-import "tiktoken_ext.openai_public" `
            --hidden-import "tiktoken_ext" `
            main.py

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KaraokeAI_Pro_EXE
          path: dist/KaraokeAI_Studio_Pro.exe
